### PR TITLE
French translation review.

### PR DESCRIPTION
**Pull request by trebmuh**
Following https://github.com/FrancescoCeruti/linux-show-player/issues/38#issuecomment-262809218 advice. Hope that helps.
@aroomthedoomed : You're translation was really good! I've been making some changes/fixes. I hope that helps you. Feel free to comment those changes.

### CODE REVIEW

**Comment by trebmuh** [comment]
Please note that I wasn't able to test a build of it since I'm running a Debian Jessie and it's not supported reading at https://github.com/FrancescoCeruti/linux-show-player/releases

**Comment by aroomthedoomed** [comment]
@trebmuh thanks for the corrections. it's a lot more accurate now.

but it seems like they are other files the reviews, like :

/lisp/modules/action_cues/i18n/action_cues_fr.ts
/lisp/modules/gst_backend/i18n/gst_backend_fr.ts
/lisp/modules/media_info/i18n/media_info_fr.ts
/lisp/modules/midi/i18n/midi_fr.ts
/lisp/modules/replay_gain/i18n/replay_gain_fr.ts
/lisp/modules/uri_changer/i18n/uri_changer_fr.ts

/lisp/plugins/controller/i18n/controller_fr.ts
/lisp/plugins/synchronizer/i18n/synchronizer_fr.ts
/lisp/plugins/triggers/i18n/triggers_fr.ts


they are a lot shorter though ;)

**Comment by trebmuh** [comment]
To @FrancescoCeruti and @aroomthedoomed : done.
Hope that helps.

**Comment by FrancescoCeruti** [comment]
@trebmuh don't worry ;)

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
