### PR TITLE
Update French translation to 100%

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by FrancescoCeruti** [comment]
Ok the files are working. I've notice I've missed to generate the source file for a module `lisp/modules/presets`, if you commit the changes directly on this branch (so you don't need to open a new pull-request) then I'll merge and push to transifex :)

**Comment by trebmuh** [comment]
@FrancescoCeruti : I'm using the github web interface. I didn't see a way to merge my fork (where the patch-3 branch is coming from) with the new master with the lisp/modules/presets you updated. Then, it seems I've got no way to add something to the patch-3 PR which would contains the newly updated lisp/modules/presets. Could you please merge this PR here, then I can erase my fork, then fork from the newly updated master and submit an new patch ?
(or maybe you know a method with the github web interface to rebase from your master branch maybe?)

**Comment by FrancescoCeruti** [comment]
@trebmuh I think you can create a pull-request in your fork, towards a branch from the upstream repository (my master), and merge into it.
Then you commit as usual into your `patch-3` branch and the PR it's "update" automatically.

**Comment by trebmuh** [comment]
@FrancescoCeruti thanks for the tips. I didn't know about this possibility. Here you go, I hope it's been done on the right way. Let me know if not.

**Comment by FrancescoCeruti** [comment]
Everything works:+1:
I've notice that you have changed `timecode` to `code temporel`, probably it should be left as `timecode` since it's used to denote a "family" of standards, let me know what do you think :)

**Comment by trebmuh** [comment]
OK, awesome.

Re: "timecode/code temporel", I'm used to translate it on the (many many) free software translation I'm doing. So far, I had 0 complain about it from French users of those software so that should mean that they are not getting lost with it. I'd go for keeping it translated.

**Comment by nodiscc** [comment]
https://fr.wikipedia.org/wiki/Timecode_(temporel) both are accepted. But over years working in A/V I've never heard anyone use `code temporel`, so my vote goes for leaving it as `Timecode`.

The other item I wish you could change (from the previous PR) was `Fondu à l'ouverture/Fondu à la fermeture`. I think it would be better as `Fondu d'entrée/Fondu de sortie` (same reason as above).

**Comment by FrancescoCeruti** [comment]
@trebmuh ... so, can I merge or you want to change something?

**Comment by trebmuh** [comment]
@FrancescoCeruti : yes, you can merge as it is. I don't want to use TimeCode instead of "code temporel" since time=temps and code=code -> then timecode=code-de-temps=code temporel. Much better to translate when doing a translation rather that to adopt a foreign word while there is no need for that.
For the other, I've got to check to confirm since from memories, I've been seeing more "fondu à l'ouverture/fermeture" than "fondu en entrée/sortie" in software translation. Anyway, this one isn't a biggy so you can merge right now and we'll be able to update those string translation if needed later.

**Comment by FrancescoCeruti** [comment]
Ok :+1:

Anyway you should be able to test the application in Debian jessie right now, using the git version

**Comment by trebmuh** [comment]
Oh really @FrancescoCeruti ? Is it buildable on Jessie now ? If you say yes, I might give a try later on today.

**Comment by FrancescoCeruti** [comment]
Yes, now you can build it on Jessie :)

Il 14 feb 2017 3:43 PM, "Olivier Humbert" <notifications@github.com> ha
scritto:

**Pull request merged**
